
services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    depends_on:
      - backend

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend